import type { OmpWebPlugin, ThemeTokens } from "../types";

const classicTokens = {
  "--pi-bg": "#0d1117",
  "--pi-surface": "#161b22",
  "--pi-surface-hover": "#21262d",
  "--pi-terminal-bg": "#05070a",
  "--pi-terminal-text": "#e6edf3",
  "--pi-border": "#30363d",
  "--pi-border-muted": "#21262d",
  "--pi-text": "#e6edf3",
  "--pi-text-secondary": "#c9d1d9",
  "--pi-text-bright": "#f0f6fc",
  "--pi-muted": "#8b949e",
  "--pi-dim": "#6e7681",
  "--pi-accent": "#58a6ff",
  "--pi-accent-border": "#2f81f7",
  "--pi-selection-bg": "#0d2847",
  "--pi-success": "#3fb950",
  "--pi-success-border": "#238636",
  "--pi-success-bg": "#0f1b12",
  "--pi-success-surface": "#0f2a16",
  "--pi-success-ring": "#3fb95055",
  "--pi-warning": "#d29922",
  "--pi-warning-border": "#6e5200",
  "--pi-warning-surface": "#1f1a10",
  "--pi-danger": "#ff7b72",
  "--pi-purple": "#d2a8ff",
  "--pi-purple-border": "#a371f7",
  "--pi-purple-surface": "#21132f",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#0d1117dd",
  "--pi-bg-overlay": "#0d1117e6",
  "--pi-success-bg-overlay": "#0f1b12ee",
  "--pi-terminal-selection": "#264f78",
} satisfies ThemeTokens;

const ompWebDarkTokens = {
  "--pi-bg": "#17171a",
  "--pi-surface": "#232324",
  "--pi-surface-hover": "#2a2a2b",
  "--pi-terminal-bg": "#111113",
  "--pi-terminal-text": "rgba(255,255,255,0.9)",
  "--pi-border": "#333335",
  "--pi-border-muted": "#2a2a2b",
  "--pi-text": "rgba(255,255,255,0.9)",
  "--pi-text-secondary": "rgba(255,255,255,0.7)",
  "--pi-text-bright": "#ffffff",
  "--pi-muted": "rgba(255,255,255,0.5)",
  "--pi-dim": "rgba(255,255,255,0.3)",
  "--pi-accent": "#3C7EFF",
  "--pi-accent-border": "#306FFF",
  "--pi-selection-bg": "#1a2540",
  "--pi-success": "#00b42a",
  "--pi-success-border": "#009a29",
  "--pi-success-bg": "#0a2018",
  "--pi-success-surface": "#0d2a1e",
  "--pi-success-ring": "#00b42a55",
  "--pi-warning": "#ff7d00",
  "--pi-warning-border": "#d26c00",
  "--pi-warning-surface": "#1e1508",
  "--pi-danger": "#f53f3f",
  "--pi-purple": "#a871f5",
  "--pi-purple-border": "#7c3cff",
  "--pi-purple-surface": "#1c1030",
  "--pi-overlay": "#0008",
  "--pi-shadow-soft": "#0006",
  "--pi-shadow": "#0008",
  "--pi-shadow-strong": "#000b",
  "--pi-bg-overlay-soft": "#17171add",
  "--pi-bg-overlay": "#17171ae6",
  "--pi-success-bg-overlay": "#0a2018ee",
  "--pi-terminal-selection": "#2e3a5a",
} satisfies ThemeTokens;

const ompWebLightTokens = {
  "--pi-bg": "#f0f1f5",
  "--pi-surface": "#ffffff",
  "--pi-surface-hover": "#e8eaed",
  "--pi-terminal-bg": "#1a1a1c",
  "--pi-terminal-text": "rgba(255,255,255,0.9)",
  "--pi-border": "#e5e6eb",
  "--pi-border-muted": "#eff0f2",
  "--pi-text": "#1d2129",
  "--pi-text-secondary": "#4e5969",
  "--pi-text-bright": "#000000",
  "--pi-muted": "#86909c",
  "--pi-dim": "#c9cdd4",
  "--pi-accent": "#165DFF",
  "--pi-accent-border": "#0e4de0",
  "--pi-selection-bg": "#e8f0ff",
  "--pi-success": "#00b42a",
  "--pi-success-border": "#009a29",
  "--pi-success-bg": "#e8f8ee",
  "--pi-success-surface": "#d4f2de",
  "--pi-success-ring": "#00b42a55",
  "--pi-warning": "#ff7d00",
  "--pi-warning-border": "#d26c00",
  "--pi-warning-surface": "#fff3e8",
  "--pi-danger": "#f53f3f",
  "--pi-purple": "#7c3cff",
  "--pi-purple-border": "#5e20d8",
  "--pi-purple-surface": "#f0ebff",
  "--pi-overlay": "#1d212966",
  "--pi-shadow-soft": "#1d212922",
  "--pi-shadow": "#1d212933",
  "--pi-shadow-strong": "#1d212944",
  "--pi-bg-overlay-soft": "#f0f1f5dd",
  "--pi-bg-overlay": "#f0f1f5e6",
  "--pi-success-bg-overlay": "#e8f8eeee",
  "--pi-terminal-selection": "#4a5568",
} satisfies ThemeTokens;

export const themePackPlugin: OmpWebPlugin = {
  apiVersion: 1,
  name: "OMP Themes",
  activate: () => ({
    contributions: {
      themes: [
        {
          id: "omp-web-dark",
          name: "OMP Dark",
          description: "Dark OMP palette.",
          order: 10,
          colorScheme: "dark",
          tokens: ompWebDarkTokens,
        },
        {
          id: "omp-web-light",
          name: "OMP Light",
          description: "Light OMP palette.",
          order: 20,
          colorScheme: "light",
          tokens: ompWebLightTokens,
        },
        {
          id: "classic",
          name: "OMP Classic",
          description: "The original OMP dark palette.",
          order: 30,
          colorScheme: "dark",
          tokens: classicTokens,
        },
      ],
      themePairs: [
        {
          id: "omp-web",
          name: "OMP",
          description: "Follow the system light/dark preference with OMP themes.",
          order: 10,
          light: "omp-web-light",
          dark: "omp-web-dark",
        },
      ],
    },
  }),
};
